apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../compose-manifests/docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: specs
  name: specs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: specs
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../compose-manifests/docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: specs
    spec:
      containers:
        - image: milovanovicsnikola/specs:v1
          name: specs
          ports:
            - containerPort: 50000
          resources: {}
          env:
            - name: PYTHONUNBUFFERED
              value: '1'
      restartPolicy: Always
status: {}
