apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: resourcereplicacontroller
spec:
  generateSelector: true
  parentResource:
    apiVersion: elfak.rs/v1
    resource: resourcereplicas
  childResources:
    - apiVersion: v1
      resource: pods
      updateStrategy:
        method: Recreate
  hooks:
    sync:
      webhook:
        url: http://192.168.1.4:8080/sync
