apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcereplicas.elfak.rs
spec:
  group: elfak.rs
  version: v1
  names:
    kind: ResourceReplica
    plural: resourcereplicas
    singular: resourcereplica
  scope: Namespaced
  subresources:
    status: {}
