apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: myapp1
  name: rest
spec:
  ports:
  - name: rest
    port: 8001
    targetPort: 8001
  selector:
    app: myapp
  type: NodePort
status:
  loadBalancer: {}
