apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    app: myapp
  name: rest-metrics
spec:
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
  selector:
    app: myapp
  type: NodePort
status:
  loadBalancer: {}
